# Generated by Django 4.0.2 on 2022-02-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], default='PENDING', max_length=155),
        ),
    ]
