# Generated by Django 4.0.2 on 2022-02-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='ticket',
            field=models.IntegerField(default=1),
        ),
    ]
