# Generated by Django 4.0.2 on 2022-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_discussion_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='answer',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
