# Generated by Django 4.0.2 on 2022-02-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_discussion_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
