# Generated by Django 4.0.2 on 2022-02-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='answer',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
